### ISSUE TITLE
ReadStationFile(STNFIL)

### ISSUE THREAD

**Issue by MohKag** [Lucas-guida/trackingARO#9]
Returns a Python “named tuple” with the parameters defined below. This function reads
the station parameters file and returns the values in degrees and meters for geographical
coordinates, degrees for az/el limits and deg/min for maximum az/el speeds.

**Comment by Lucas-guida** [comment]
The station.dat file comes in this format we must correct it

ARO
45.95550333333333
281.9269597222222
260.42
-4.0
1
0.0, 9.0, 89.0
3.0
3.0

Note the azimuth/elevation limits list should start with 0, be an ordered list and the software should
append a 360 azimuth point (same elevation limits as for 0) to allow interpolation as required over the
full range of azimuth angles. A second, more general example for the Petrie Building would be as follows:

**Comment by MohKag** [comment]
Function modified for change.
